<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-08ELHDF" ignored="0" name="test1" tests="5" failures="3" timestamp="23 十一月 2018 03:24:23 GMT" time="0.112" errors="0">
  <testcase name="test1" time="0.016" classname="com.webtest.demo.Demo"/>
  <testcase name="test2" time="0.019" classname="com.webtest.demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.webtest.demo.Demo.test2(Demo.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.004" classname="com.webtest.demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [1] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [4]
at com.webtest.demo.Demo.test3(Demo.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.003" classname="com.webtest.demo.Demo2"/>
  <testcase name="test3" time="0.002" classname="com.webtest.demo.Demo2">
    <failure type="java.lang.AssertionError" message="expected [1] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [4]
at com.webtest.demo.Demo2.test3(Demo2.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- test1 -->
